Add support for multiple assembly dialects in the base parser
mockingbirdnest/OSACA pull request #2
Opened 2024-10-21 20:53 UTC by pleroy

The parser and related code currently know about the ISA.  But of course the point of this effort is to support a different assembly dialect for the `x86` ISA.  While it would have been possible to lump the two pieces of information in a "fake ISA" (say, `x86ATT` and `x86INTEL`, this seems like an abuse of the data model.  A clean separation seems preferable.

This PR is adding the dialect (1) as a  command line flag and (2) in the heuristic detection done by the base parser.  It also plumbs the parameter everywhere necessary.  There is a new parser, but it doesn't implement any method other than a constructor at this point.

2024-10-25 03:07 UTC, eggrobin requested changes

2024-10-25 03:07 UTC, eggrobin commented on osaca/osaca.py
> +SUPPORTED_DIALECTS = {
Let’s call them syntaxes.

2024-10-25 03:07 UTC, eggrobin commented on osaca/osaca.py
> +    arch = args.arch if args.arch is not None else DEFAULT_ARCHS[detected_isa]
```suggestion
    arch = args.arch if args.arch else DEFAULT_ARCHS[detected_isa]
```

2024-10-25 03:07 UTC, eggrobin commented on osaca/osaca.py
> +    dialect = args.dialect if args.dialect is not None else detected_dialect
```suggestion
    dialect = args.dialect if args.dialect else detected_dialect
```

2024-10-25 03:07 UTC, eggrobin commented on osaca/osaca.py
> +    } if args.arch == None and args.dialect == None
```suggestion
    } if not args.arch and not args.dialect
```

Same elsewhere.

2024-10-26 15:41 UTC, eggrobin approved these changes

2024-10-26 15:41 UTC, eggrobin commented on osaca/osaca.py
> +    if (args.syntax is not None and args.arch is not None and
More is not None.

2024-10-26 16:05 UTC, pleroy commented on osaca/osaca.py
> +    if (args.syntax is not None and args.arch is not None and
Done, but note that this is the style above.  (I don't think that I should go cleaning up that code.)

2024-10-26 16:07 UTC, eggrobin approved these changes

2024-10-26 16:11 UTC, merged